spring.application.name=server
spring.datasource.url=jdbc:mariadb://mariadb:3306/kubenbois
spring.datasource.username=kubenbois
spring.datasource.password=u00vE&^f6Tgs>b;{
spring.jpa.hibernate.ddl-auto=validate