spring.application.name=server
spring.datasource.url=jdbc:mariadb://localhost:3306/kubenbois?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=validate

jwt.secret=oonSs@w%r0W7wP*b3bGswargY^pEz3I3!0WjU&Eu6l*@VTPY8seB^bdrkXsIUMOM0z1P4qJk#eZ?xQ&gLSo^p6iViF8Rb77@79N!pNNm^coY?!CM&!jMGXKkAg7st@@Sb%qQxdJ7CLn!g!!V4$fSsHuQsxtFYZS85Ki&%q@F9WPSZQbsxKS^wQa5yACu%?M@h4lvbuCgi3q!e#TH3&JQ6mM5MaiZe6ThRsZ2gYzeTkA6XZNI7qGz2n3DYX
jwt.token-expiration=300000
jwt.token-refresh-expiration=3024000000

frontend.url=http://localhost:4200